### ISSUE TITLE
Explain || when it occurs first (at least in a footnote)

### ISSUE THREAD

**Issue by hmmueller** [crypto101/book#140]
|| is the concatenation operator - but concatentaion is expressed differently in other areas, e.g. as + (many program languages), a center dot or nothing (in formal languages), a period (in Perl), even as || (in standard SQL, but not in Microsoft's SQL Server).

Also, either tell us that 
- it's a byte operator (so x || 0 || y inserts 8 zero bits between x and y); or 
- it is a bit operator (so x || 0 || y inserts a single zero bit between x and y); or
- you don't use it very exactly, so context makes it clear what is meant (like in N || 0... || k), or it is not really important. 
  All three versions are ok - but it'd be nice for the reader to know what is meant ...

**Comment by trackpick** [comment]
I ran into this as well, and I don't think the current resolution is sufficient. It's still weird to have concatenation explained after it has been used many times already (even if some uses are on bytes and some on bits).

I would go for the third option in the original comment above and place that where concatenation is first used, which appears to be the Encryption oracle attack on ECB.
