### ISSUE TITLE
Typo's for chapter 5

### ISSUE THREAD

**Issue by toonn** [crypto101/book#242]
The next to last sentence on page 22 reads: "... because she has no idea *of* the key bit...", of should be if. Also the figure on this page is nearly the same as the one on the next and isn't referred to in the text, I suggest you either drop it or add explanation.
On page 26 the first (half)sentence ends with "... somewhere *in*.", the in should be dropped.
All of this is based on the pdf generated from commit e2353eb.

I'm currently going through the book and plan on submitting an issue of the typo's I notice for each chapter if this is annoying or impractical please let me know. If these issues are still open by the time I finish the book I'm prepared to fix all of them in a pull request.

**Comment by lvh** [comment]
Pull requests would be great! Smaller ones are better than bigger ones ,although a big one is fine as long as they're all unambiguous improvements (i.e. a bunch of spelling fixes, but not some spelling fixes and some rewordings).
