### ISSUE TITLE
Figure 6.1 (page 32) has only 14 nodes while according to the text, there should be 16 nodes

### ISSUE THREAD

**Issue by eeshangarg** [crypto101/book#248]
Hi!

Page 32:
```
Figure 6.1 illustrates the blocks that the cipher operates on.
```
and (also, below I think it should be ```Each node is``` and not ```Each nodes is```),
```
Figure 6.1: All of the 16 nodes operated on by the block cipher. Each
nodes is designated by a hexadecimal digit.
```
but there are only 14 nodes in the above-mentioned figure and other similar figures in the same chapter (Block Ciphers); apart from page 32, please take a look at pages 33, 34, and 35.

Let me know what you think! :-)

Thanks!
Eeshan

**Comment by lvh** [comment]
These issues appear to be addressed in master. I guess it's time for a new release.

![screen shot 2015-05-24 at 10 45 21 am](https://cloud.githubusercontent.com/assets/97816/7788888/0015a5b4-0202-11e5-8db6-4a49b5fac269.png)
![screen shot 2015-05-24 at 10 45 28 am](https://cloud.githubusercontent.com/assets/97816/7788889/00161a58-0202-11e5-9679-5eddf6177a70.png)
![screen shot 2015-05-24 at 10 45 32 am](https://cloud.githubusercontent.com/assets/97816/7788890/00164f82-0202-11e5-847a-5a342006b473.png)
