### ISSUE TITLE
Missing/incorrect pronouns on page 73 and 74

### ISSUE THREAD

**Issue by eeshangarg** [crypto101/book#250]
Hi!

Page 73, last line (2nd item in the numbered list),
```
2. The pseudorandom generator, which produces they actual keystream
bytes from the state array S produced by the key scheduling al-
```
I think the word "they" after "produces" in the above sentence should be replaced by the word "the", like so,
```
2. The pseudorandom generator, which produces the actual keystream
bytes from the state array S produced by the key scheduling al-
```

Page 74, line 1, (which is a continuation of the above mentioned list item),
```
The pseudorandom generator itself also modifies the
state array as produces keystream bytes.
```
I think there should be the pronoun "it" after "..state array as", like so,
```
The pseudorandom generator itself also modifies the
state array as it produces keystream bytes.
```
Thanks! :-)
Eeshan

**Comment by lvh** [comment]
Thanks for reporting this bug. However, both of these issues are already resolved in master.
