### ISSUE TITLE
Inconsistent case when describing XOR diagram

### ISSUE THREAD

**Issue by frewsxcv** [crypto101/book#254]
Consider this section:

---

![screen shot 2015-06-13 at 5 12 20 pm](https://cloud.githubusercontent.com/assets/416575/8146496/6e9eeaf2-11ef-11e5-9afc-edb11db29c40.png)

---

The diagram uses uppercase letters, the paragraph below uses lowercase letters. I haven't read enough technical papers to know if this is intentional. If it's not intentional, I'd be willing to make the appropriate changes to make the letter case consistent.

**Comment by lvh** [comment]
Resolved in linked commit.
