### ISSUE TITLE
Appendix/Modular arithmetics - coprimes section factual error

### ISSUE THREAD

**Issue by CthulhuDen** [crypto101/book#259]
`Two numbers are called coprime when their greatest common
divisor is 1, or, to put it in another way, they don’t share any prime
factors. Since the only prime factor a prime has is itself, that means
that a prime is coprime to every other number.`

The last statement is not true, either it was meant to say `a prime is coprime to every other prime number` or `a prime is coprime to every number which it does not divide`.

**Comment by lvh** [comment]
Good catch, thanks! Working on a patch now.
