### ISSUE TITLE
written on a physical, paper pad?

### ISSUE THREAD

**Issue by genericmoniker** [crypto101/book#260]
In the "One time pads" section.

Original:

The sequence is called a pad because it was originally a physical, paper pad.

Proposed:

The sequence is called a pad because it was originally written on a physical, paper pad.

Or maybe "printed on" rather than "written on"?

**Comment by lvh** [comment]
Thanks for submitting an issue!

I'm not sure I'm getting it. I guess the distinction is between the abstract notion of a bunch of information (the key) and the physical object, which that sentence is trying to nullify?

**Comment by genericmoniker** [comment]
The existing sentence just came across a little strange to me. In picturing something like this [physical pad](http://www.cryptomuseum.com/crypto/otp.htm), the "sequence" to me is the numbers printed on the paper rather than the pad of paper itself. But maybe that's either me being pedantic or misunderstanding the historical usage.

**Comment by lvh** [comment]
Okay, that makes sense :)

**Comment by lvh** [comment]
I'm going to try "recorded" instead of written/printed, since that doesn't imply the method.
