### ISSUE TITLE
Paragraph AES attacks is not comprehensible

### ISSUE THREAD

**Issue by schlamar** [crypto101/book#265]
These two paragraphs are weird. The first one indicates that AES is vulnerable against a related-key attack while the second one says that this should never happen in practice. Somehow this is really confusing and you get no clear idea what a related-key attack actually is.

    There are no practical attacks known against AES. While there
    have been some developments in the last few years, most of them
    involve related-key attacks [ 10 ], some of them only on reduced-round
    versions of AES [9].
    A related key attack involves making some predictions about how
    AES will behave with two different keys with some specific mathe-
    matical relation. Those predictions provide some information about
    what identical (input, output) pairs will look like under those different
    keys. Most of these attacks attempt to recover the key entirely, com-
    pletely breaking the encryption. While an ideal block cipher wouldn’t
    be vulnerable to a related key attack, no system in the real world should
    ever end up with such related keys. If it does, things have gone so

**Comment by lvh** [comment]
Would it help if this section pointed out that cryptographic keys should be cryptographically random, and therefore the odds that you incidentally picked two keys with such a property are nonexistent?

**Comment by hmmueller** [comment]
Yes :-)

**Comment by naman** [comment]
Suggestion:

`some of them only on reduced-round versions of AES [9].` I think it would be fair to add a footnote for the definition of a "round" or a "(will be discussed later)". First time readers might get a little confused here.

**Comment by lvh** [comment]
@naman I've added a footnote to that effect in tagged commit.
