### ISSUE TITLE
8.5 paragraph 2

### ISSUE THREAD

**Issue by colwem** [crypto101/book#273]
> Alice and Bob will have a shared secret, but the secret is shared with Mallory.

This confused me at first thought maybe it meant that there was one secret shared between 3 people.  Would have been clearer if worded like "There will now be two shared secrets, one between Alice and Mallory and one between Mallory and Bob."

**Comment by lvh** [comment]
Thanks! I've adjusted the sentence in tagged commit; let me know if that helps.

**Comment by colwem** [comment]
Yeah, that's good.
