### ISSUE TITLE
8.5 paragraph 3

### ISSUE THREAD

**Issue by colwem** [crypto101/book#274]
> To make matters worse, even if one of the two participants was somehow aware that this was going on, they would have no way to get the other party to believe them. After all: Mallory performed the successful Diffie-Hellman exchange with the unwitting victim, she has all the correct shared secrets. Bob, on the other hand, just has some secrets shared with Mallory, but he has no way to prove that to Alice.
As far as Alice knows, Bob just chose a few random numbers 

The last half of that.  I have no idea what this is saying.  

I can easily guess why Mallory would make it impossible to for either Alice or Bob to prove that Mallory is in the middle.  Because if Bob discovers Mallory and tries to go around Mallory and notify Alice he can't do so using the shared secret key between him and Alice since he doesn't actually have that key.  As far as Alice is concerned Mallory is Bob and Bob is a stranger.  Likewise any notification Bob tries to do through Mallory can just be intercepted by Mallory.

Also, what's the difference between Eve and Mallory?  Why switch between them?  Do they represent different kinds of third parties?

**Comment by lvh** [comment]
I'm surprised to hear you say that you have no idea what this is saying, because you just described perfectly what it's saying.

Eve is merely an eavesdropper, while Mallory is a more general malicious agent. The specific difference is that Eve (being an eavesdropper) only ever listens to messages sent across the wire, while Mallory is (or at least can be) an active participant. Typically Eve is only used to clarify that a protocol is vulnerable _even_ to a passive adversary (since Mallory is strictly more powerful).

I'm open to suggestions for introducing those personae.

**Comment by lvh** [comment]
(While I'm open to suggestions for introducing people, that seems like a different ticket. Since it seems like you understood this one fine, I'll close this -- but if you have specific suggestions for making it clearer, please feel free to comment on this ticket.)

**Comment by colwem** [comment]
Oh the purpose of this issue just to give you feedback about something that needs improvement in the book.  It's not specifically because I need help understanding.  I "know what it means" simply because I can reason about the situation.  The paragraph itself didn't help me get there though.  I still have no idea what that paragraph is saying at the end there.  "A few random numbers"?  Huh?.  I think the paragraph needs improvement.

Basically in all of these issues I'm opening it's like 80% to help you out and 20% to get further clarification.

**Comment by lvh** [comment]
OK. I can't think of a way to rewrite this paragraph to be clearer; do you have any suggestions?

**Comment by lvh** [comment]
I came up with:

```
odified   Crypto101.org
@@ -2528,7 +2528,7 @@ party to believe them. After all: Mallory performed the successful
 Diffie-Hellman exchange with the unwitting victim, she has all the
 correct shared secrets. Bob, on the other hand, just has some secrets
 shared with Mallory, but he has no way to prove that to Alice. As far
-as Alice knows, Bob just chose a few random numbers.
+as Alice can tell, Bob just chose a few random numbers.
```

... which feels ... a bit better. I also added:

```
 There's no way to link any key that Bob has with
any key that Alice has.
```

Hopefully that clarifies the sentence.

**Comment by colwem** [comment]
I think you need specify that bob is sending a message to Alice using his key and alice is trying to decrypt it using her key and the result is random numbers.  I also think your use of "victim", "all" and "some" earlier in the paragraph is confusing.  I would re-write it to something like:

> Mallory performed the successful Diffie-Hellman exchange with the unwitting **victims**, she has ~~all~~ **both** the correct shared secrets. Bob, on the other hand, just has ~~some secrets~~ **the secret** shared with Mallory, but he has no way to prove that to Alice.  **Any message he sends directly to Alice using his key will just look like random numbers to Alice**.

**Comment by lvh** [comment]
"victim -> victims" doesn't work; the victim is _unwitting_, and the sentence directly before it says that one of them knows what's going on, so there's only one unwitting victim (Alice, in this case). Bob isn't unwitting; he's the one who hypothetically knows what's going on.

Suggesting an encryption key sounds like it makes assumptions about the protocol, rather than the mechanism. DH gets you some shared secret (some entropy), but that's not typically your encryption key, but rather the entropy that lets you produce a set of keys. Saying that the decryption would look like random numbers is also generally (and usually) incorrect: generally you use that entropy to produce a key for an AEAD mode or produce two keys (encryption and authentication), either way, encryption will fail, not produce a bunch of noise.

I've rewritten the paragraph a little to:

> To make matters worse, even if one of the two participants was somehow aware
> that this was going on, they would have no way to get the other party to
> believe them. After all: Mallory performed the successful Diffie-Hellman
> exchange with the unwitting victim, she has all the correct shared
> secrets. Bob has no shared secrets with Alice, just with Mallory; there's no
> way for him to prove that he's the legitimate participant. As far as Alice can
> tell, Bob just chose a few random numbers. There's no way to link any key that
> Bob has with any key that Alice has.

(see linked commit). does that help at all?

**Comment by colwem** [comment]
Ok so I only know what you've told me to this point in the book.  This I think is the value of me giving you immediate feedback as I read it.  I have a perspective you can't possibly have because you carry with you a context that includes a massive amount of knowledge on this subject so it's bound to be harder for you to notice when there's missing information. I on the other hand notice it immediately because my brain fails to make sense of it.

> DH gets you some shared secret (some entropy), but that's not typically your encryption key, but rather the entropy that lets you produce a set of keys. 

So in my context the only secrets I know about are keys, I have no idea what entropy is (outside of thermodynamics). So to me secret = key and in this case there's only one so being plural is confusing. 

> Saying that the decryption would look like random numbers is also generally (and usually) incorrect: generally you use that entropy to produce a key for an AEAD mode or produce two keys (encryption and authentication)

Yeah, this may be true, but so far I only know of encryption.  They use DH to share a key which they then use to encrypt messages which they can send to each other.  I don't understand entropy, I have no idea what AEAD means, and although you've mentioned authentication many times I still don't really know what that means either.  What I mean is authentication can either mean "make sure the message hasn't gotten changed" or "make sure the message is from who I think it's from" or both, I'm not sure, they're probably equivalent definitions, but I'm not sure.

So at this point when you take into account all of that stuff in trying to make this sentence rigorously correct it just makes it confusing to me.  My brain just goes "secrets? what secrets? there's only one", "numbers? what numbers, why is bob trying to prove mallory's existence with numbers?  What?".   "You must mean he's trying to send her a secret message encrypted with his and mallories key but Alice can't read it because she doesn't have the key and so instead she just reads random noise"  Basically anything else just doesn't make any sense to me.   So if that's not actually the message you're trying to convey then you should probably change it.

> As far as Alice can tell, Bob just chose a few random numbers.

It's really this sentence that is like 90% of the problem.  To me it's such a nonsequetor I can't even really explain why I have a problem with it. It just seems to come out of the blue with no leadup.  It's like "Wait, what, when did this happen? What is Alice looking at?  Bob chose? Chose for what? when did he chose? Was he actually sending her a particular number but to alice it looked like a random number?  Or was he sending her a message that ended up garballed? Did he even send her a message?  I have to assume so but it's never actually said so maybe I'm missing something, maybe there was no message. etc.

**Comment by lvh** [comment]
Gotcha. I'll try and come up with a better way to phrase that (possibly just elide it) -- but I also want to make sure that it still makes sense if you review it after reading e.g. the chapter on authentication, authenticated encryption, protocols using authenticated encryption. It's not quite up to the point of rigor in the mathematical sense; once you made it through those chapters I'm convinced that would stick out like a sore thumb.
