### ISSUE TITLE
Problems in A.8 Discrete logarithm

### ISSUE THREAD

**Issue by postboy** [crypto101/book#281]
The following appears on page 222.

1. First of all, there's definitely a typo there:
"As with division, if you start from the definition as the inverse of a different operator, it’s easy to come up with examples.  For example, since 3^6 = 9 (mod 15), we can define 9 = log(3, 6) (mod 15)."
Indeed, 3^6 (mod 15) = 9, but it means that 6 = log(3, 9) (mod 15)!

2. Second, this is not a general defenition:
"Just like subtraction is the inverse of addition, and division is the inverse of multiplication, logarithms are the inverse of exponentiation. In regular arithmetic, e^x = y, if x = log(e, y). The equivalent of this in modular arithmetic is commonly called a ”discrete logarithm”."
Well, it's a defenition of *natural* logarithm, not the logarithm itself. I believe that it would be better to say "In regular arithmetic, a^x = y, if x = log(a, y)."

**Comment by lvh** [comment]
Hi! Thanks for your comments :)

Re: 1; definitely a typo, good catch. Will fix.

Re: 2; if I understand correctly, you're just suggesting a change of variables from *e* to *a*, and your specific gripe is with the letter *e*?

**Comment by lvh** [comment]
Re: 2; I didn't think it was confusing because I don't really specify what that base is other than that variable, but if it was confusing to you then that's good enough for me. I've attached some commits; please let me know if you feel they don't resolve the issue.
