### ISSUE TITLE
Layout problem in A.6 Exponentiation by squaring

### ISSUE THREAD

**Issue by postboy** [crypto101/book#282]
Page 214 of the book ends like this.

![default](https://cloud.githubusercontent.com/assets/12019610/16578864/7d0ba282-42a5-11e6-925a-66c55df67228.png)

This is probably can be solved by number with smaller value, with smaller font or maybe with switching from tabs to spaces between terms.

**Comment by lvh** [comment]
I've fixed it by switching the array column separator. I don't know if you looked at the source code at all, but that's LaTeX, not tabs and spaces :)

Thanks!
