### ISSUE TITLE
Wrong equations in 11.5 One-time MACs

### ISSUE THREAD

**Issue by postboy** [crypto101/book#283]
Specifically, I will talk about "Re-using a and b" section, pages 134-135.

![default](https://cloud.githubusercontent.com/assets/12019610/16582087/6d9f26c4-42b5-11e6-8712-02fce6964846.png)

Additional proof: [here](http://web.mit.edu/6.857/OldStuff/Fall97/lectures/lecture3.pdf), "One-time Key k" section, pages 2-3.

**Comment by lvh** [comment]
Thanks for the reference! However, that PDF doesn't seem to work that equation out at all, it just says "two equations, two variables, we're done".

**Comment by postboy** [comment]
I totally agree, just wanted to make my arguements more sound with that:

![image](https://cloud.githubusercontent.com/assets/12019610/16588260/05e74c2e-42d7-11e6-98fb-0e0268ae000a.png)

**Comment by postboy** [comment]
As you probably noted, the point is not in the reference itself. The point is that in several places plus sign should be changed to minus, and attached PDF just agrees with this!
