### ISSUE TITLE
Unprocessed $ symbols

### ISSUE THREAD

**Issue by postboy** [crypto101/book#285]
Special symbol $ means cursive in raw LaTeX text, but sometimes it suddenly occurs in PDF totally unprocessed, just as "dollar sign-something-dollar sign", not as "something in cursive":
Page 145: $L$-bit prime
Page 169: $x$-coordinate
Page 212: $n$’s prime factors

Probably it's because there's no space/newline/tabulation after the second dollar sign.

**Comment by lvh** [comment]
Hm, yeah, this is a problem with org-mode's lexing strategy. Some of them can be rewritten, but I'm not sure what to do about L-bit prime.

**Comment by lvh** [comment]
Managed to work around it with org native formatting :) Thanks!
