### ISSUE TITLE
Inconsistent variable usage in "pronunciation" for discrete log

### ISSUE THREAD

**Issue by vicariggio** [crypto101/book#290]
On page 222 (in pdf based on a596660):
![discrete log intro](https://cloud.githubusercontent.com/assets/20338548/16653964/e05d5dee-4453-11e6-8b53-0e50d4679d37.png)
In the "pronunciation" for x = log y, the role of x and y is swapped.

**Comment by lvh** [comment]
Whoops, thanks, that got introduced quite recently.
