### ISSUE TITLE
What's the deal with the ECB secret suffix S?

### ISSUE THREAD

**Issue by devinrsmith** [crypto101/book#291]
The first time we learn about the ECB secret suffix `S` is when you introduce the oracle attack against ECB. The suffix wasn't mentioned in the original ECB construction, and it's unclear how breaking the suffix helps in breaking ECB more generally.

I'm assuming that `S` is used to pad the final plaintext block if it is shorter than the block size?

How does breaking `S` help us in breaking `k`?  

Haven't read further than this yet, so maybe these questions are answered later.

**Comment by lvh** [comment]
The secret suffix is not part of ECB; breaking the secret suffix is the goal of the attacker in this example. The oracle will encrypt the attacker's message with the suffix appended; the suffix is supposed to be secret; the attacker will learn the suffix.

**Comment by lvh** [comment]
As for "it's not clear how this breaks ECB generally" -- it doesn't; it's a specific attack scenario. It aims to demonstrate that an ECB encryption oracle leaks data. FWIW, while this is an abstracted example and a real ECB oracle is "messier", it is not unrealistic; this attack can be used against plenty of real ECB-using systems. (In particular, it just matters that there's some secret data after attacker-controlled data; it doesn't matter if there's something before the attacker-controlled data or after the secret.)

Does that help?

**Comment by lvh** [comment]
(Apologies, did not intend to close.)

**Comment by devinrsmith** [comment]
Yes, makes sense. Wasn't obvious to me that `S` was part of some specific implementation utilizing ECB. Might be able to make the text clearer in this regards. Will leave it up to you to close as you see fit.

Thanks!

**Comment by lo-fo** [comment]
I got the same trouble grasping what this S is and why does it comes out of nowhere in the book.
