### ISSUE TITLE
Problem in 16.2 The web of trust

### ISSUE THREAD

**Issue by postboy** [crypto101/book#292]
I'm not sure is it a typo or just a text ambiguity.

Page 198: "Of course, this is only the default way to use OpenPGP. There’s nothing stopping you from shipping a particular public key with some software, **and using that to sign messages**, just like you might want to do with TLS."

Is "that" in this sentence stands for "OpenPGP" or for "a particular public key"? Second variant doesn't makes much sense: you should have a *private* key for signing, not public, but it's not a good idea to ship it with software anyway.

Dear lvh, maybe you should change "sign" to "encrypt" or "that" to "OpenPGP" here?

**Comment by lvh** [comment]
That sentence is a little confusing. What I'm trying to convey is that you can use the same RSA token for both OpenPGP and e.g. SSH, TLS...

**Comment by lvh** [comment]
I've adjusted the wording in attached commit; let me know if that resolves the issue. Apologies for previous (deleted) comment -- I was thinking of a different section.
