### ISSUE TITLE
Problems in 17.2 Key exchange

### ISSUE THREAD

**Issue by postboy** [crypto101/book#293]
I'm sorry for mixing this all together in one issue. I can split it to several distinct issues, if it will be more handy for you, lvh!

***
***
***

![default](https://cloud.githubusercontent.com/assets/12019610/16911653/65dba70e-4ce8-11e6-8440-30277b801804.png)

![image](https://cloud.githubusercontent.com/assets/12019610/16912117/0e02ddba-4ceb-11e6-8837-e14a44ecba4c.png)

![image](https://cloud.githubusercontent.com/assets/12019610/16912157/417afeca-4ceb-11e6-9ca5-93723ccd3a8f.png)

On first screenshot you can see wrong layout (similar problems: #282, #287).

***
***
***

Second, underlined "B"s and "A"s above should be changed to "s_B" and "s_A", because this is the notation we use for private keys in this section (page 201):

![image](https://cloud.githubusercontent.com/assets/12019610/16911786/2c6ce0d6-4ce9-11e6-8d5c-01d5632cf3f7.png)

***
***
***

Third, "M" and "MAC", "E" and "AES"  function are used interchangeably throughout the section:

![image](https://cloud.githubusercontent.com/assets/12019610/16912020/91ab91b2-4cea-11e6-89f5-fa21f2e42fa3.png)

![image](https://cloud.githubusercontent.com/assets/12019610/16912694/5cfa095e-4cee-11e6-80bd-8343493666bf.png)

Original intention was to use "M" and "E" for that purposes:

![image](https://cloud.githubusercontent.com/assets/12019610/16912721/93367af2-4cee-11e6-96dc-51d70d26e05a.png)

***
***
***

Forth, missed paratheses here:

![image](https://cloud.githubusercontent.com/assets/12019610/16912305/f50ad6b8-4ceb-11e6-8d9c-80b801eb2597.png)

***
***
***

And finally, first problem also occurs on page 204:

![image](https://cloud.githubusercontent.com/assets/12019610/16911914/eacba6e8-4ce9-11e6-8244-9f08cc877962.png)

**Comment by lvh** [comment]
I've pushed some commits that ref this. Currently rebuilding to see what happens.

**Comment by lvh** [comment]
Awesome, I think this is resolved.

Thank you so much for the stream of useful issues. How, if at all, would you like to be credited in the introduction to the book?

**Comment by postboy** [comment]
Thank you for great book that was a real pleasure to read! Your work is really great in it's cryptography part and just unbeatably awesome in cryptanalysis part -- everything is explained very well and clear. I'm looking forward for future versions with new sections and I wish you all the good in this work!

A credit in this book would be a real honour for me! I'd like to be credited as "Ivan Zuboff".
