### ISSUE TITLE
ARX

### ISSUE THREAD

**Issue by zx2c4** [crypto101/book#297]
You go into detail about AES and RC4. What about going into detail about ChaCha too? ARX is simple and interesting.

**Comment by EdOverflow** [comment]
Just as a matter of interest, where would you explain ChaCha and ARX in the book? @lvh mentions ChaCha [here](https://github.com/crypto101/book/blob/master/Crypto101.org#salsa20).

**Comment by zx2c4** [comment]
The place where he already mentions ChaCha.

**Comment by EdOverflow** [comment]
OK, if I find time I'll write about ARX where ChaCha is mentioned.

**Comment by lvh** [comment]
Thanks @EdOverflow !

**Comment by EdOverflow** [comment]
**Update:** The ARX section can now be found in the Salsa20 chapter. https://github.com/crypto101/book/blob/master/Crypto101.org#salsa20 (https://github.com/crypto101/book/commit/afdf7e7b29537a1349f18f449aa30e8de6c3857a).

**Comment by lvh** [comment]
Looks like this can be closed :)
