### ISSUE TITLE
XOR cancelling "proved" without using associativity

### ISSUE THREAD

**Issue by sjoerdjob** [crypto101/book#298]
In version 3f89ec3, chapter 5.2, it is proved that `a ^ b ^ a = b` by some simple steps.

However, these steps are supported by the fact that `(a ^ b) ^ c = a ^ (b ^ c)` which needs to at least be mentioned.

(Used the `^` for the notation of XOR here, I hope that's clear.)

**Comment by lvh** [comment]
I'm traveling, so it's a little tricky for me to check out the PDF right now. Knowing me (and granted, I wrote that a while ago); I'd assume I proved it by saying it's a symmetrical operation, but still keeping left-to-right evaluation.

**Comment by sjoerdjob** [comment]
I just double-checked. In 5.2 the evaluation order is not even mentioned. Also, the related property of "dropping the parentheses" is also used in 5.5.

**Comment by lvh** [comment]
I've added the property in attached commit. Thanks :)
