### ISSUE TITLE
Technicality on the definition of a block

### ISSUE THREAD

**Issue by akiekintveld** [crypto101/book#315]
In Chapter 6, on page 31, it states: 

> The plaintext and ciphertext blocks are a sequence of _bytes_."

I believe "_bytes_" should be "_bits_" here.

**Comment by akiekintveld** [comment]
I fixed the definition and opened a pull request: #316

**Comment by lvh** [comment]
Thanks! I'm wondering if there are any ciphers where the distinction matters, but I suppose Hasty Pudding counts.

**Comment by lvh** [comment]
Closed by #316.
