### ISSUE TITLE
figure placement incorrect

### ISSUE THREAD

**Issue by trackpick** [crypto101/book#325]
In the PDF I'm reading (0.4.0-102-g9e48035) I see this sentence: "In the illustration, this is block CR1:". Presumably the intent is that the illustration immediately follows this line but it actually appears on the next page. Either that or the colon was added by mistake.

**Comment by EdOverflow** [comment]
This issue has already been addressed over at https://github.com/crypto101/book/issues/284.

**Comment by lvh** [comment]
Yep, closing as dup.
