### ISSUE TITLE
Chapter 7, Page 70: Sentence may be unclear?

### ISSUE THREAD

**Issue by mikeevmm** [crypto101/book#340]
Hi, first of all, thank you for this book, it's been really interesting and accessible!

On page 69/70, the book goes into further decrypting a block using a padding attack, after a first padding has been found. However, it's not very clear for me how this should be done in practice: although I understand that

![eq](https://latex.codecogs.com/gif.latex?D%28C_i%29%5Bb%5D%5Coplus%20r_b%20%3D%2001%20%5CRightarrow%20D%28C_i%29%5Bb%5D%20%5Coplus%20r_b%20%5Coplus%2001%20%5Coplus%2002%20%3D%2002)

it's then said that

> The attacker uses **that value** for the last byte.

What value? And wouldn't this flip value be in plaintext? How could we know the equivalent cyphertext to inject?

Finaly, if we are to create **R'** such that ![eq2](https://latex.codecogs.com/gif.latex?R%27%20%3D%20r_1%20r_2%20%5Ccdots%20r_%7Bb-1%7D%20r%27_b), being that it's CBC mode, wouldn't brute forcing be impossible, being that we'd only get one chance to XOR R' with R||C_i ?

(I see how these might all be issues with my understanding, so sorry in advance!)

**Comment by lvh** [comment]
Heya; I appear to have missed the documentation for this. There's some new language here that might clarify your question.

The attacker modifies a ciphertext block R, but that gets XORd with the _decryption_ of a target block C, so valid padding tells the attacker something about the value at the last byte: we know that it produced valid padding, and we know what it was XORd with to produce valid padding, so we can undo the XOR and produce the unencrypted byte.

Does that make sense?
