### ISSUE TITLE
Update PDF on crypto101.io

### ISSUE THREAD

**Issue by gusutabopb** [crypto101/book#341]
Hi, thanks for the great book! I want to read the latest version, but I'm having some trouble building the book from source. It'd be greatly appreciated if the PDF at crypto101.io were updated to the latest v0.6.0 (78a72534eb54396c191fd62729816e9a8fb7c827)! It is still v0.4.0 (9e48035d991f3ad3d0689aa6e923be4bee8ee674), which is almost 1.5 years old now.

Thanks!

**Comment by lvh** [comment]
What's the URL you see for the PDF? It should be https://github.com/crypto101/crypto101.github.io/raw/master/Crypto101.pdf, updated last week: https://github.com/crypto101/crypto101.github.io/commit/448468fc0224098c01265b1a6df0f557f978ba5e

**Comment by lvh** [comment]
Whoops; should be: updated 2 months ago, because it links to master, not gh-pages - but it still definitely shouldn't be 0.4.0... I'll look into it.

**Comment by lvh** [comment]
This is fixed; thanks for the bug report :)
