### ISSUE TITLE
Differential Cryptanalysis was known to the DES inventors

### ISSUE THREAD

**Issue by meadori** [crypto101/book#344]
In the `SubBytes` sub-section of section 6.2 there is a footnote on the susceptibility of DES to differential attacks:

> In its defense, differential attacks were not publicly known back when DES was designed.

It is my understanding that it was not generally known, but was known by the NSA and the DES designers at IBM.  The NSA compelled IBM to not disclose any information that would help others learn about the technique.  Wikipedia discusses this (as well as Levy's Crypto book):

1. https://en.wikipedia.org/wiki/Differential_cryptanalysis
2. https://en.wikipedia.org/wiki/Data_Encryption_Standard#Attacks_faster_than_brute_force

The SBoxes were, in fact, designed to resist differential attacks.

**Comment by meadori** [comment]
Also, I think it was *linear cryptanalysis* that Sbox 5 was susceptible to:

https://en.wikipedia.org/wiki/Linear_cryptanalysis

**Comment by lvh** [comment]
Yup, that sentence is unclear. I was referring to public knowledge, but you are correct that DES was still redesigned to be resilient against differential cryptanalysis. I will clarify the passage.

**Comment by lvh** [comment]
Whoa, I see what you mean. I have no idea how that got past. You're absolutely correct.

**Comment by lvh** [comment]
I have resolved the issue, rolled a new PDF and uploaded it.
