### ISSUE TITLE
Published epub version

### ISSUE THREAD

**Issue by derekriemer** [crypto101/book#355]
Hi:
I was viewing the main site, at https://www.crypto101.io/, and there is a mention of an EPUB version. There isn't a link to an epub version, and I was curious if this is a mistake on the site?
I'm a blind software engineer, and mathematics in epub are far superior to mathematics in PDF for screen readers, so I was hoping to find an EPUB version of the book available.
Thanks

**Comment by lvh** [comment]
Hi Derek!

Ugh, I'm so sorry. That line is struck through (which I didn't appreciate might not work well for screenreaders before you pointed it out).

This isn't a mistake: I've been unable to get epub working satisfactorily.

Out of interest, I found multiple ways to do math in epubs and most of them appeared to be raster, which sounds like it'd be totally useless for people with sight challenges. When you say "mathematics in epubs are far superior" does that mean `mathml`? I'd be happy to take that into consideration if I ever get the epub version working :)

**Comment by derekriemer** [comment]
yes. Ideally mathml would be the best format to get working. an alternative, although inferior method is to provide la tex as the alt-text for the images in epub format.
Cheers

**Comment by gliptak** [comment]
https://github.com/crypto101/book/issues/62

**Comment by lvh** [comment]
Yep closing this in favor of that one
