### ISSUE TITLE
Citations not referenced warnings

### ISSUE THREAD

**Issue by gliptak** [crypto101/book#381]
Build https://travis-ci.com/github/crypto101/book/builds/186566487 shows:

```
/repo/src/zreferences.rst: WARNING: Citation [nist:sp800-90a] is not referenced.
/repo/src/zreferences.rst: WARNING: Citation [bellarecanettikrawczyk:keyinghash] is not referenced.
/repo/src/zreferences.rst: WARNING: Citation [cryptoeprint:2004:199] is not referenced.
```

Are these be removed from https://github.com/crypto101/book/blob/master/src/Crypto101.bib ?

**Comment by multun** [comment]
these could be removed, but I figured @lvh might wanna keep these around just in case they end up being used in later additions

**Comment by lvh** [comment]
Yeah, exactly. It's almost weird these aren't getting used now, they're pretty important reference works.

**Comment by lvh** [comment]
Maybe a good compromise: comment them? They'll be easy to get back, and no warnings.
