### ISSUE TITLE
better wording for description?

### ISSUE THREAD

**Issue by ousia** [crypto101/book#445]
@lvh,

I have just read when paging through (emphasis is mine):

> Like TLS, OpenPGP is a hybrid cryptosystem. Users have key pairs consisting of a public key and a private key. Public key algorithms are used both for signing and encryption. Symmetric key algorithms are used to encrypt the message body; the symmetric key itself is protected using [public-key encryption](javascript:void(0)). This also makes it easy to encrypt a message for multiple recipients: *only the secret key has to be encrypted multiple times*.

I wonder whether this would avoid the potential ambiguity:

> only the _symmetric_ key has to be encrypted multiple times.

Many thanks for your help.

**Comment by lvh** [comment]
Sure, yep, that does seem a little better :) Patch welcome!
